
if(WIN32)
	if(NOT "${CMAKE_SIZEOF_VOID_P}" STREQUAL "4" AND NOT "${CMAKE_SIZEOF_VOID_P}" STREQUAL "8")
		message(FATAL_ERROR "CMAKE_SIZEOF_VOID_P=${CMAKE_SIZEOF_VOID_P}. Unknown platform")
	else()
		if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "4")
			set(ZLIB_PLATFOTM_NAME win32)
		else()
			set(ZLIB_PLATFOTM_NAME x64)	
		endif()
	endif()
	add_library(ZLIB::ZLIB STATIC IMPORTED)
	set_target_properties(ZLIB::ZLIB PROPERTIES
		#INTERFACE_COMPILE_DEFINITIONS "OPENSSL_STATIC"
		INTERFACE_INCLUDE_DIRECTORIES "${ZLIB_ROOT}/include/"
		IMPORTED_LOCATION_DEBUG "${ZLIB_ROOT}/lib/zlibstaticd_${ZLIB_PLATFOTM_NAME}.lib"
		IMPORTED_LOCATION_RELEASE "${ZLIB_ROOT}/lib/zlibstatic_${ZLIB_PLATFOTM_NAME}.lib"
		IMPORTED_LOCATION_MINSIZEREL "${ZLIB_ROOT}/lib/zlibstatic_${ZLIB_PLATFOTM_NAME}.lib"
		IMPORTED_LOCATION_RELWITHDEBINFO "${ZLIB_ROOT}/lib/zlibstatic_${ZLIB_PLATFOTM_NAME}.lib"
	)
else()
	find_package(ZLIB)
endif()
